# Generated by Django 5.0.2 on 2024-02-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPurchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('quantity_purchased', models.DecimalField(decimal_places=4, max_digits=19)),
                ('amount_purchased', models.DecimalField(decimal_places=4, max_digits=19)),
                ('date_purchased', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CryptoSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('quantity_sold', models.DecimalField(decimal_places=4, max_digits=19)),
                ('amount_sold', models.DecimalField(decimal_places=4, max_digits=19)),
                ('date_sold', models.DateField()),
            ],
        ),
    ]
