# Generated by Django 5.0.2 on 2024-02-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptopurchased',
            name='amount_invested',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cryptopurchased',
            name='quantity_purchased',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19),
        ),
    ]
